#!/usr/bin/env bash
#
# Exit immediately if a command exits with a non-zero status.
set -o errexit	# same as 'set -e'
# Treat unset variables as an error when substituting.
set -o nounset	# same as 'set -u'
set -o pipefail	# the return value of a pipeline is the status of
                # the last command to exit with a non-zero status,
                # or zero if no command exited with a non-zero status
                
# Saving IFS and set it to new
SAVEIFS=$IFS
IFS="$(printf '\n\t')"

##---Functions
fdate() {
	date +[%Y-%m-%dT%H:%M:%S]
}

# Boolean variables

# Variables
APP_NAME="Script"
APP_VER="0.0.1"
SELF=$(readlink -f "${BASH_SOURCE[0]}")
BASENAME=$(basename "${SELF}")

_SHELL="$(echo "${SHELL}" | sed -E 's/.*\/([a-z]+)$/\1/')"
_SHELL_PATH="$(command -v "${_SHELL}")"

##---MAIN---##
function main {
	# body
	# ...
  if [[ $# -eq 0 ]]; then

    printf '%s\tver. %s\n' "${APP_NAME}" "${APP_VER}"
    printf ' FILE:\t%s  (%s)\n' "${SELF}" "${BASENAME}"
    printf 'SHELL:\t%s  (%s)\n\n' "${_SHELL}" "${_SHELL_PATH}"
    fdate
  fi

	IFS="${SAVEIFS}"
	return 0
}

main "${@}" || return 1

# vim: ts=2 sw=2 et
